# Generated by Django 3.1 on 2020-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('Breads', 'Brs'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Vegetables', 'Vegetables'), ('Meat&Fish', 'Meat&Fish'), ('Sweets', 'Sweets')], max_length=200, null=True),
        ),
    ]
